### ISSUE TITLE
Integrate address search results

### ISSUE THREAD

**Issue by DaveBathnes** [Geovation/usemap-reactjs#20]
### **Feature**

The address search bar should return real results from searches. Searches could be by full or partial address.

**How to do it** 

As we are demoing a 'real-life' app, where there are likely to be many API calls, we have to code this in a robust way where the structure of the app is scalable. The solution will need to:

* Hold a base URL (e.g. https://api.example.com) address endpoint in config files that will support multiple environments (e.g. Test/Dev/Production) 
* Hold a config file where individual endpoints for the base URL can be configured for each service (e.g. { "Places": "/places" })
* Create a separate code library that wraps the axios function to make get and post requests using the base URL, and is retrieves individual endpoints (all this can be held in an ```api``` directory)
* Create a separate React Hook to implement Places (held in a ```hooks``` directory). This should return an array of place name labels (full address) and location coordinates.
* Use the Places hook in Search.js component to populate results in Autocomplete fields

**Acceptance criteria**

* Solution should have individual build configs that can switch between localhost/PythonAnywhere/AWS
* The search functionality should be tested and working

**Comment by branmkam** [comment]
I'd also note that we should be able to scroll through the top 20 or so options on the autocomplete search bar, since most of the time the first option won't be the one that someone is looking for.

**Comment by DaveBathnes** [comment]
@branmkam The API currently limits to 30 results so for now we can just return those and then have a think how we present large sets of results. We could have scrolling or paging but we'll also need to considering ordering of results, unless the API does it for us in a good way.

I'll write another ticket to capture all the requirements around result display.
